export const UPDATE_COLOR = "UPDATE_COLOR";
export const LOAD_COLORS = "LOAD_COLORS";

export const LOAD_CLOTHES = "LOAD_CLOTHES";
export const DELETE_CLOTHING = "DELETE_CLOTHING";
export const UPDATE_CLOTHING = "UPDATE_CLOTHING";
export const SAVE_CLOTHING = "SAVE_CLOTHING";
